-- Restores the names used when the expanded catalog was first introduced.
UPDATE products AS product
SET name = translated.name
FROM (VALUES
    ('lettuce', 'Lechuga'),
    ('spinach', 'Espinacas'),
    ('courgette', 'Calabacín'),
    ('aubergine', 'Berenjena'),
    ('cauliflower', 'Coliflor'),
    ('cabbage', 'Col o repollo'),
    ('green_beans', 'Judías verdes'),
    ('asparagus', 'Espárragos'),
    ('peas', 'Guisantes'),
    ('sweet_potato', 'Boniato'),
    ('pumpkin', 'Calabaza'),
    ('celery', 'Apio'),
    ('leek', 'Puerro'),
    ('ginger', 'Jengibre'),
    ('parsley', 'Perejil'),
    ('coriander', 'Cilantro'),
    ('pear', 'Peras'),
    ('grapes', 'Uvas'),
    ('kiwi', 'Kiwis'),
    ('pineapple', 'Piña'),
    ('watermelon', 'Sandía'),
    ('peaches', 'Melocotones'),
    ('blueberries', 'Arándanos'),
    ('frozen_vegetables', 'Verduras congeladas'),
    ('turkey', 'Pavo'),
    ('minced_meat', 'Carne picada'),
    ('pork_chops', 'Chuletas de cerdo'),
    ('sausages', 'Salchichas'),
    ('cooked_ham', 'Jamón cocido'),
    ('serrano_ham', 'Jamón serrano'),
    ('sliced_turkey', 'Fiambre de pavo'),
    ('salmon', 'Salmón'),
    ('hake', 'Merluza'),
    ('tuna_steaks', 'Filetes de atún'),
    ('prawns', 'Langostinos o gambas'),
    ('frozen_fish', 'Pescado congelado'),
    ('tofu', 'Tofu'),
    ('veggie_burgers', 'Hamburguesas vegetales'),
    ('natural_yogurt', 'Yogur natural'),
    ('greek_yogurt', 'Yogur griego'),
    ('fruit_yogurt', 'Yogur de frutas'),
    ('plant_milk', 'Bebida vegetal'),
    ('cream', 'Nata para cocinar'),
    ('cottage_cheese', 'Queso fresco'),
    ('mozzarella', 'Mozzarella'),
    ('grated_cheese', 'Queso rallado'),
    ('cream_cheese', 'Queso crema'),
    ('margarine', 'Margarina'),
    ('egg_whites', 'Claras de huevo'),
    ('dairy_desserts', 'Postres lácteos'),
    ('oats', 'Copos de avena'),
    ('breadcrumbs', 'Pan rallado'),
    ('tortilla_wraps', 'Tortillas de trigo'),
    ('crackers', 'Crackers'),
    ('quinoa', 'Quinoa'),
    ('couscous', 'Cuscús'),
    ('noodles', 'Fideos'),
    ('lentils', 'Lentejas'),
    ('chickpeas', 'Garbanzos'),
    ('canned_peas', 'Guisantes en conserva'),
    ('canned_tuna', 'Atún en conserva'),
    ('canned_sardines', 'Sardinas en conserva'),
    ('tomato_sauce', 'Tomate frito'),
    ('crushed_tomato', 'Tomate triturado'),
    ('tomato_paste', 'Concentrado de tomate'),
    ('mayonnaise', 'Mayonesa'),
    ('ketchup', 'Kétchup'),
    ('mustard', 'Mostaza'),
    ('vinegar', 'Vinagre'),
    ('sunflower_oil', 'Aceite de girasol'),
    ('sugar', 'Azúcar'),
    ('brown_sugar', 'Azúcar moreno'),
    ('baking_powder', 'Levadura química'),
    ('yeast', 'Levadura de panadería'),
    ('cocoa_powder', 'Cacao en polvo'),
    ('jam', 'Mermelada'),
    ('peanut_butter', 'Crema de cacahuete'),
    ('dried_fruit', 'Fruta deshidratada'),
    ('cereal_bars', 'Barritas de cereales'),
    ('crisps', 'Patatas fritas'),
    ('frozen_pizza', 'Pizza congelada'),
    ('sparkling_water', 'Agua con gas'),
    ('decaf_coffee', 'Café descafeinado'),
    ('herbal_tea', 'Infusiones'),
    ('iced_tea', 'Té frío'),
    ('energy_drinks', 'Bebidas energéticas'),
    ('tonic_water', 'Tónica'),
    ('isotonic_drink', 'Bebida isotónica'),
    ('kombucha', 'Kombucha'),
    ('cider', 'Sidra'),
    ('sparkling_wine', 'Cava'),
    ('spirits', 'Bebidas espirituosas'),
    ('laundry_detergent', 'Detergente para ropa'),
    ('fabric_softener', 'Suavizante'),
    ('stain_remover', 'Quitamanchas'),
    ('bleach', 'Lejía'),
    ('disinfectant', 'Desinfectante'),
    ('multipurpose_cleaner', 'Limpiador multiusos'),
    ('glass_cleaner', 'Limpiacristales'),
    ('degreaser', 'Desengrasante'),
    ('toilet_cleaner', 'Limpiador de WC'),
    ('dishwasher_tablets', 'Pastillas lavavajillas'),
    ('dishwasher_salt', 'Sal para lavavajillas'),
    ('dishcloths', 'Bayetas'),
    ('rubber_gloves', 'Guantes de limpieza'),
    ('aluminium_foil', 'Papel de aluminio'),
    ('baking_paper', 'Papel de horno'),
    ('cling_film', 'Film transparente'),
    ('paper_towels', 'Papel de cocina'),
    ('napkins', 'Servilletas'),
    ('tissues', 'Pañuelos'),
    ('deodorant', 'Desodorante'),
    ('shower_gel', 'Gel de ducha'),
    ('conditioner', 'Acondicionador'),
    ('dental_floss', 'Hilo dental'),
    ('mouthwash', 'Colutorio'),
    ('toothbrush_heads', 'Cepillos o recambios dentales'),
    ('cotton_pads', 'Discos de algodón'),
    ('feminine_hygiene', 'Higiene femenina'),
    ('sunscreen', 'Protector solar'),
    ('insect_repellent', 'Repelente de insectos'),
    ('first_aid_kit', 'Material de primeros auxilios'),
    ('light_bulbs', 'Bombillas'),
    ('matches', 'Cerillas o encendedor'),
    ('candles', 'Velas'),
    ('air_freshener', 'Ambientador')
) AS translated(code, name)
WHERE product.code = translated.code;

