-- Expands the fixed catalog with the products approved in
-- docs/CATALOG_PROPOSAL.md. Existing pantries receive the new items with their
-- catalog defaults and an initial OK stock status.
INSERT INTO products (id, code, name, image, default_category, default_type, sort_order) VALUES
    (gen_random_uuid(), 'lettuce', 'Lechuga', 'lettuce.svg', 'FRUIT_VEG', 'ESSENTIAL', 58),
    (gen_random_uuid(), 'spinach', 'Espinacas', 'spinach.svg', 'FRUIT_VEG', 'SECONDARY', 59),
    (gen_random_uuid(), 'courgette', 'Calabacín', 'courgette.svg', 'FRUIT_VEG', 'SECONDARY', 60),
    (gen_random_uuid(), 'aubergine', 'Berenjena', 'aubergine.svg', 'FRUIT_VEG', 'OTHERS', 61),
    (gen_random_uuid(), 'cauliflower', 'Coliflor', 'cauliflower.svg', 'FRUIT_VEG', 'OTHERS', 62),
    (gen_random_uuid(), 'cabbage', 'Col o repollo', 'cabbage.svg', 'FRUIT_VEG', 'OTHERS', 63),
    (gen_random_uuid(), 'green_beans', 'Judías verdes', 'green_beans.svg', 'FRUIT_VEG', 'SECONDARY', 64),
    (gen_random_uuid(), 'asparagus', 'Espárragos', 'asparagus.svg', 'FRUIT_VEG', 'OTHERS', 65),
    (gen_random_uuid(), 'peas', 'Guisantes', 'peas.svg', 'FRUIT_VEG', 'SECONDARY', 66),
    (gen_random_uuid(), 'sweet_potato', 'Boniato', 'sweet_potato.svg', 'FRUIT_VEG', 'OTHERS', 67),
    (gen_random_uuid(), 'pumpkin', 'Calabaza', 'pumpkin.svg', 'FRUIT_VEG', 'OTHERS', 68),
    (gen_random_uuid(), 'celery', 'Apio', 'celery.svg', 'FRUIT_VEG', 'OTHERS', 69),
    (gen_random_uuid(), 'leek', 'Puerro', 'leek.svg', 'FRUIT_VEG', 'SECONDARY', 70),
    (gen_random_uuid(), 'ginger', 'Jengibre', 'ginger.svg', 'FRUIT_VEG', 'SECONDARY', 71),
    (gen_random_uuid(), 'parsley', 'Perejil', 'parsley.svg', 'FRUIT_VEG', 'SECONDARY', 72),
    (gen_random_uuid(), 'coriander', 'Cilantro', 'coriander.svg', 'FRUIT_VEG', 'OTHERS', 73),
    (gen_random_uuid(), 'pear', 'Peras', 'pear.svg', 'FRUIT_VEG', 'SECONDARY', 74),
    (gen_random_uuid(), 'grapes', 'Uvas', 'grapes.svg', 'FRUIT_VEG', 'OTHERS', 75),
    (gen_random_uuid(), 'kiwi', 'Kiwis', 'kiwi.svg', 'FRUIT_VEG', 'SECONDARY', 76),
    (gen_random_uuid(), 'pineapple', 'Piña', 'pineapple.svg', 'FRUIT_VEG', 'OTHERS', 77),
    (gen_random_uuid(), 'watermelon', 'Sandía', 'watermelon.svg', 'FRUIT_VEG', 'OTHERS', 78),
    (gen_random_uuid(), 'peaches', 'Melocotones', 'peaches.svg', 'FRUIT_VEG', 'OTHERS', 79),
    (gen_random_uuid(), 'blueberries', 'Arándanos', 'blueberries.svg', 'FRUIT_VEG', 'OTHERS', 80),
    (gen_random_uuid(), 'frozen_vegetables', 'Verduras congeladas', 'frozen_vegetables.svg', 'FRUIT_VEG', 'SECONDARY', 81),
    (gen_random_uuid(), 'turkey', 'Pavo', 'turkey.svg', 'MEAT_FISH', 'SECONDARY', 82),
    (gen_random_uuid(), 'minced_meat', 'Carne picada', 'minced_meat.svg', 'MEAT_FISH', 'SECONDARY', 83),
    (gen_random_uuid(), 'pork_chops', 'Chuletas de cerdo', 'pork_chops.svg', 'MEAT_FISH', 'OTHERS', 84),
    (gen_random_uuid(), 'sausages', 'Salchichas', 'sausages.svg', 'MEAT_FISH', 'OTHERS', 85),
    (gen_random_uuid(), 'cooked_ham', 'Jamón cocido', 'cooked_ham.svg', 'MEAT_FISH', 'SECONDARY', 86),
    (gen_random_uuid(), 'serrano_ham', 'Jamón serrano', 'serrano_ham.svg', 'MEAT_FISH', 'OTHERS', 87),
    (gen_random_uuid(), 'sliced_turkey', 'Fiambre de pavo', 'sliced_turkey.svg', 'MEAT_FISH', 'SECONDARY', 88),
    (gen_random_uuid(), 'salmon', 'Salmón', 'salmon.svg', 'MEAT_FISH', 'SECONDARY', 89),
    (gen_random_uuid(), 'hake', 'Merluza', 'hake.svg', 'MEAT_FISH', 'SECONDARY', 90),
    (gen_random_uuid(), 'tuna_steaks', 'Filetes de atún', 'tuna_steaks.svg', 'MEAT_FISH', 'OTHERS', 91),
    (gen_random_uuid(), 'prawns', 'Langostinos o gambas', 'prawns.svg', 'MEAT_FISH', 'OTHERS', 92),
    (gen_random_uuid(), 'frozen_fish', 'Pescado congelado', 'frozen_fish.svg', 'MEAT_FISH', 'SECONDARY', 93),
    (gen_random_uuid(), 'tofu', 'Tofu', 'tofu.svg', 'MEAT_FISH', 'SECONDARY', 94),
    (gen_random_uuid(), 'veggie_burgers', 'Hamburguesas vegetales', 'veggie_burgers.svg', 'MEAT_FISH', 'OTHERS', 95),
    (gen_random_uuid(), 'natural_yogurt', 'Yogur natural', 'natural_yogurt.svg', 'DAIRY_EGGS', 'ESSENTIAL', 96),
    (gen_random_uuid(), 'greek_yogurt', 'Yogur griego', 'greek_yogurt.svg', 'DAIRY_EGGS', 'SECONDARY', 97),
    (gen_random_uuid(), 'fruit_yogurt', 'Yogur de frutas', 'fruit_yogurt.svg', 'DAIRY_EGGS', 'SECONDARY', 98),
    (gen_random_uuid(), 'plant_milk', 'Bebida vegetal', 'plant_milk.svg', 'DAIRY_EGGS', 'SECONDARY', 99),
    (gen_random_uuid(), 'cream', 'Nata para cocinar', 'cream.svg', 'DAIRY_EGGS', 'SECONDARY', 100),
    (gen_random_uuid(), 'cottage_cheese', 'Queso fresco', 'cottage_cheese.svg', 'DAIRY_EGGS', 'SECONDARY', 101),
    (gen_random_uuid(), 'mozzarella', 'Mozzarella', 'mozzarella.svg', 'DAIRY_EGGS', 'SECONDARY', 102),
    (gen_random_uuid(), 'grated_cheese', 'Queso rallado', 'grated_cheese.svg', 'DAIRY_EGGS', 'SECONDARY', 103),
    (gen_random_uuid(), 'cream_cheese', 'Queso crema', 'cream_cheese.svg', 'DAIRY_EGGS', 'OTHERS', 104),
    (gen_random_uuid(), 'margarine', 'Margarina', 'margarine.svg', 'DAIRY_EGGS', 'OTHERS', 105),
    (gen_random_uuid(), 'egg_whites', 'Claras de huevo', 'egg_whites.svg', 'DAIRY_EGGS', 'OTHERS', 106),
    (gen_random_uuid(), 'dairy_desserts', 'Postres lácteos', 'dairy_desserts.svg', 'DAIRY_EGGS', 'OTHERS', 107),
    (gen_random_uuid(), 'oats', 'Copos de avena', 'oats.svg', 'DRY_CANNED', 'SECONDARY', 108),
    (gen_random_uuid(), 'breadcrumbs', 'Pan rallado', 'breadcrumbs.svg', 'DRY_CANNED', 'SECONDARY', 109),
    (gen_random_uuid(), 'tortilla_wraps', 'Tortillas de trigo', 'tortilla_wraps.svg', 'DRY_CANNED', 'SECONDARY', 110),
    (gen_random_uuid(), 'crackers', 'Crackers', 'crackers.svg', 'DRY_CANNED', 'OTHERS', 111),
    (gen_random_uuid(), 'quinoa', 'Quinoa', 'quinoa.svg', 'DRY_CANNED', 'SECONDARY', 112),
    (gen_random_uuid(), 'couscous', 'Cuscús', 'couscous.svg', 'DRY_CANNED', 'SECONDARY', 113),
    (gen_random_uuid(), 'noodles', 'Fideos', 'noodles.svg', 'DRY_CANNED', 'SECONDARY', 114),
    (gen_random_uuid(), 'lentils', 'Lentejas', 'lentils.svg', 'DRY_CANNED', 'SECONDARY', 115),
    (gen_random_uuid(), 'chickpeas', 'Garbanzos', 'chickpeas.svg', 'DRY_CANNED', 'SECONDARY', 116),
    (gen_random_uuid(), 'canned_peas', 'Guisantes en conserva', 'canned_peas.svg', 'DRY_CANNED', 'OTHERS', 117),
    (gen_random_uuid(), 'canned_tuna', 'Atún en conserva', 'canned_tuna.svg', 'DRY_CANNED', 'SECONDARY', 118),
    (gen_random_uuid(), 'canned_sardines', 'Sardinas en conserva', 'canned_sardines.svg', 'DRY_CANNED', 'OTHERS', 119),
    (gen_random_uuid(), 'tomato_sauce', 'Tomate frito', 'tomato_sauce.svg', 'DRY_CANNED', 'ESSENTIAL', 120),
    (gen_random_uuid(), 'crushed_tomato', 'Tomate triturado', 'crushed_tomato.svg', 'DRY_CANNED', 'SECONDARY', 121),
    (gen_random_uuid(), 'tomato_paste', 'Concentrado de tomate', 'tomato_paste.svg', 'DRY_CANNED', 'OTHERS', 122),
    (gen_random_uuid(), 'mayonnaise', 'Mayonesa', 'mayonnaise.svg', 'DRY_CANNED', 'SECONDARY', 123),
    (gen_random_uuid(), 'ketchup', 'Kétchup', 'ketchup.svg', 'DRY_CANNED', 'SECONDARY', 124),
    (gen_random_uuid(), 'mustard', 'Mostaza', 'mustard.svg', 'DRY_CANNED', 'OTHERS', 125),
    (gen_random_uuid(), 'vinegar', 'Vinagre', 'vinegar.svg', 'DRY_CANNED', 'SECONDARY', 126),
    (gen_random_uuid(), 'sunflower_oil', 'Aceite de girasol', 'sunflower_oil.svg', 'DRY_CANNED', 'SECONDARY', 127),
    (gen_random_uuid(), 'sugar', 'Azúcar', 'sugar.svg', 'DRY_CANNED', 'SECONDARY', 128),
    (gen_random_uuid(), 'brown_sugar', 'Azúcar moreno', 'brown_sugar.svg', 'DRY_CANNED', 'OTHERS', 129),
    (gen_random_uuid(), 'baking_powder', 'Levadura química', 'baking_powder.svg', 'DRY_CANNED', 'OTHERS', 130),
    (gen_random_uuid(), 'yeast', 'Levadura de panadería', 'yeast.svg', 'DRY_CANNED', 'OTHERS', 131),
    (gen_random_uuid(), 'cocoa_powder', 'Cacao en polvo', 'cocoa_powder.svg', 'DRY_CANNED', 'OTHERS', 132),
    (gen_random_uuid(), 'jam', 'Mermelada', 'jam.svg', 'DRY_CANNED', 'SECONDARY', 133),
    (gen_random_uuid(), 'peanut_butter', 'Crema de cacahuete', 'peanut_butter.svg', 'DRY_CANNED', 'SECONDARY', 134),
    (gen_random_uuid(), 'dried_fruit', 'Fruta deshidratada', 'dried_fruit.svg', 'DRY_CANNED', 'OTHERS', 135),
    (gen_random_uuid(), 'cereal_bars', 'Barritas de cereales', 'cereal_bars.svg', 'DRY_CANNED', 'OTHERS', 136),
    (gen_random_uuid(), 'crisps', 'Patatas fritas', 'crisps.svg', 'DRY_CANNED', 'OTHERS', 137),
    (gen_random_uuid(), 'frozen_pizza', 'Pizza congelada', 'frozen_pizza.svg', 'DRY_CANNED', 'OTHERS', 138),
    (gen_random_uuid(), 'sparkling_water', 'Agua con gas', 'sparkling_water.svg', 'DRINKS', 'SECONDARY', 139),
    (gen_random_uuid(), 'decaf_coffee', 'Café descafeinado', 'decaf_coffee.svg', 'DRINKS', 'SECONDARY', 140),
    (gen_random_uuid(), 'herbal_tea', 'Infusiones', 'herbal_tea.svg', 'DRINKS', 'SECONDARY', 141),
    (gen_random_uuid(), 'iced_tea', 'Té frío', 'iced_tea.svg', 'DRINKS', 'OTHERS', 142),
    (gen_random_uuid(), 'energy_drinks', 'Bebidas energéticas', 'energy_drinks.svg', 'DRINKS', 'OTHERS', 143),
    (gen_random_uuid(), 'tonic_water', 'Tónica', 'tonic_water.svg', 'DRINKS', 'OTHERS', 144),
    (gen_random_uuid(), 'isotonic_drink', 'Bebida isotónica', 'isotonic_drink.svg', 'DRINKS', 'OTHERS', 145),
    (gen_random_uuid(), 'kombucha', 'Kombucha', 'kombucha.svg', 'DRINKS', 'OTHERS', 146),
    (gen_random_uuid(), 'cider', 'Sidra', 'cider.svg', 'DRINKS', 'OTHERS', 147),
    (gen_random_uuid(), 'sparkling_wine', 'Cava', 'sparkling_wine.svg', 'DRINKS', 'OTHERS', 148),
    (gen_random_uuid(), 'spirits', 'Bebidas espirituosas', 'spirits.svg', 'DRINKS', 'OTHERS', 149),
    (gen_random_uuid(), 'laundry_detergent', 'Detergente para ropa', 'laundry_detergent.svg', 'HOME_CARE', 'ESSENTIAL', 150),
    (gen_random_uuid(), 'fabric_softener', 'Suavizante', 'fabric_softener.svg', 'HOME_CARE', 'SECONDARY', 151),
    (gen_random_uuid(), 'stain_remover', 'Quitamanchas', 'stain_remover.svg', 'HOME_CARE', 'OTHERS', 152),
    (gen_random_uuid(), 'bleach', 'Lejía', 'bleach.svg', 'HOME_CARE', 'SECONDARY', 153),
    (gen_random_uuid(), 'disinfectant', 'Desinfectante', 'disinfectant.svg', 'HOME_CARE', 'SECONDARY', 154),
    (gen_random_uuid(), 'multipurpose_cleaner', 'Limpiador multiusos', 'multipurpose_cleaner.svg', 'HOME_CARE', 'ESSENTIAL', 155),
    (gen_random_uuid(), 'glass_cleaner', 'Limpiacristales', 'glass_cleaner.svg', 'HOME_CARE', 'OTHERS', 156),
    (gen_random_uuid(), 'degreaser', 'Desengrasante', 'degreaser.svg', 'HOME_CARE', 'SECONDARY', 157),
    (gen_random_uuid(), 'toilet_cleaner', 'Limpiador de WC', 'toilet_cleaner.svg', 'HOME_CARE', 'SECONDARY', 158),
    (gen_random_uuid(), 'dishwasher_tablets', 'Pastillas lavavajillas', 'dishwasher_tablets.svg', 'HOME_CARE', 'ESSENTIAL', 159),
    (gen_random_uuid(), 'dishwasher_salt', 'Sal para lavavajillas', 'dishwasher_salt.svg', 'HOME_CARE', 'OTHERS', 160),
    (gen_random_uuid(), 'dishcloths', 'Bayetas', 'dishcloths.svg', 'HOME_CARE', 'SECONDARY', 161),
    (gen_random_uuid(), 'rubber_gloves', 'Guantes de limpieza', 'rubber_gloves.svg', 'HOME_CARE', 'OTHERS', 162),
    (gen_random_uuid(), 'aluminium_foil', 'Papel de aluminio', 'aluminium_foil.svg', 'HOME_CARE', 'SECONDARY', 163),
    (gen_random_uuid(), 'baking_paper', 'Papel de horno', 'baking_paper.svg', 'HOME_CARE', 'SECONDARY', 164),
    (gen_random_uuid(), 'cling_film', 'Film transparente', 'cling_film.svg', 'HOME_CARE', 'SECONDARY', 165),
    (gen_random_uuid(), 'paper_towels', 'Papel de cocina', 'paper_towels.svg', 'HOME_CARE', 'ESSENTIAL', 166),
    (gen_random_uuid(), 'napkins', 'Servilletas', 'napkins.svg', 'HOME_CARE', 'SECONDARY', 167),
    (gen_random_uuid(), 'tissues', 'Pañuelos', 'tissues.svg', 'HOME_CARE', 'SECONDARY', 168),
    (gen_random_uuid(), 'deodorant', 'Desodorante', 'deodorant.svg', 'HOME_CARE', 'ESSENTIAL', 169),
    (gen_random_uuid(), 'shower_gel', 'Gel de ducha', 'shower_gel.svg', 'HOME_CARE', 'ESSENTIAL', 170),
    (gen_random_uuid(), 'conditioner', 'Acondicionador', 'conditioner.svg', 'HOME_CARE', 'SECONDARY', 171),
    (gen_random_uuid(), 'dental_floss', 'Hilo dental', 'dental_floss.svg', 'HOME_CARE', 'SECONDARY', 172),
    (gen_random_uuid(), 'mouthwash', 'Colutorio', 'mouthwash.svg', 'HOME_CARE', 'SECONDARY', 173),
    (gen_random_uuid(), 'toothbrush_heads', 'Cepillos o recambios dentales', 'toothbrush_heads.svg', 'HOME_CARE', 'SECONDARY', 174),
    (gen_random_uuid(), 'cotton_pads', 'Discos de algodón', 'cotton_pads.svg', 'HOME_CARE', 'SECONDARY', 175),
    (gen_random_uuid(), 'feminine_hygiene', 'Higiene femenina', 'feminine_hygiene.svg', 'HOME_CARE', 'ESSENTIAL', 176),
    (gen_random_uuid(), 'sunscreen', 'Protector solar', 'sunscreen.svg', 'HOME_CARE', 'OTHERS', 177),
    (gen_random_uuid(), 'insect_repellent', 'Repelente de insectos', 'insect_repellent.svg', 'HOME_CARE', 'OTHERS', 178),
    (gen_random_uuid(), 'first_aid_kit', 'Material de primeros auxilios', 'first_aid_kit.svg', 'HOME_CARE', 'OTHERS', 179),
    (gen_random_uuid(), 'light_bulbs', 'Bombillas', 'light_bulbs.svg', 'HOME_CARE', 'OTHERS', 180),
    (gen_random_uuid(), 'matches', 'Cerillas o encendedor', 'matches.svg', 'HOME_CARE', 'OTHERS', 181),
    (gen_random_uuid(), 'candles', 'Velas', 'candles.svg', 'HOME_CARE', 'OTHERS', 182),
    (gen_random_uuid(), 'air_freshener', 'Ambientador', 'air_freshener.svg', 'HOME_CARE', 'OTHERS', 183)
ON CONFLICT (code) DO NOTHING;

INSERT INTO pantry_items (pantry_id, product_id, status, product_type, category)
SELECT pantry.id, product.id, 'OK', product.default_type, product.default_category
FROM pantries AS pantry
CROSS JOIN products AS product
WHERE product.code IN (
    'lettuce', 'spinach', 'courgette', 'aubergine', 'cauliflower', 'cabbage',
    'green_beans', 'asparagus', 'peas', 'sweet_potato', 'pumpkin', 'celery',
    'leek', 'ginger', 'parsley', 'coriander', 'pear', 'grapes',
    'kiwi', 'pineapple', 'watermelon', 'peaches', 'blueberries', 'frozen_vegetables',
    'turkey', 'minced_meat', 'pork_chops', 'sausages', 'cooked_ham', 'serrano_ham',
    'sliced_turkey', 'salmon', 'hake', 'tuna_steaks', 'prawns', 'frozen_fish',
    'tofu', 'veggie_burgers', 'natural_yogurt', 'greek_yogurt', 'fruit_yogurt', 'plant_milk',
    'cream', 'cottage_cheese', 'mozzarella', 'grated_cheese', 'cream_cheese', 'margarine',
    'egg_whites', 'dairy_desserts', 'oats', 'breadcrumbs', 'tortilla_wraps', 'crackers',
    'quinoa', 'couscous', 'noodles', 'lentils', 'chickpeas', 'canned_peas',
    'canned_tuna', 'canned_sardines', 'tomato_sauce', 'crushed_tomato', 'tomato_paste', 'mayonnaise',
    'ketchup', 'mustard', 'vinegar', 'sunflower_oil', 'sugar', 'brown_sugar',
    'baking_powder', 'yeast', 'cocoa_powder', 'jam', 'peanut_butter', 'dried_fruit',
    'cereal_bars', 'crisps', 'frozen_pizza', 'sparkling_water', 'decaf_coffee', 'herbal_tea',
    'iced_tea', 'energy_drinks', 'tonic_water', 'isotonic_drink', 'kombucha', 'cider',
    'sparkling_wine', 'spirits', 'laundry_detergent', 'fabric_softener', 'stain_remover', 'bleach',
    'disinfectant', 'multipurpose_cleaner', 'glass_cleaner', 'degreaser', 'toilet_cleaner', 'dishwasher_tablets',
    'dishwasher_salt', 'dishcloths', 'rubber_gloves', 'aluminium_foil', 'baking_paper', 'cling_film',
    'paper_towels', 'napkins', 'tissues', 'deodorant', 'shower_gel', 'conditioner',
    'dental_floss', 'mouthwash', 'toothbrush_heads', 'cotton_pads', 'feminine_hygiene', 'sunscreen',
    'insect_repellent', 'first_aid_kit', 'light_bulbs', 'matches', 'candles', 'air_freshener'
)
ON CONFLICT (pantry_id, product_id) DO NOTHING;

