-- Keeps the expanded catalog consistent with the original English UI.
UPDATE products AS product
SET name = translated.name
FROM (VALUES
    ('lettuce', 'Lettuce'),
    ('spinach', 'Spinach'),
    ('courgette', 'Courgette'),
    ('aubergine', 'Aubergine'),
    ('cauliflower', 'Cauliflower'),
    ('cabbage', 'Cabbage'),
    ('green_beans', 'Green beans'),
    ('asparagus', 'Asparagus'),
    ('peas', 'Peas'),
    ('sweet_potato', 'Sweet potatoes'),
    ('pumpkin', 'Pumpkin'),
    ('celery', 'Celery'),
    ('leek', 'Leeks'),
    ('ginger', 'Ginger'),
    ('parsley', 'Parsley'),
    ('coriander', 'Coriander'),
    ('pear', 'Pears'),
    ('grapes', 'Grapes'),
    ('kiwi', 'Kiwis'),
    ('pineapple', 'Pineapple'),
    ('watermelon', 'Watermelon'),
    ('peaches', 'Peaches'),
    ('blueberries', 'Blueberries'),
    ('frozen_vegetables', 'Frozen vegetables'),
    ('turkey', 'Turkey'),
    ('minced_meat', 'Minced meat'),
    ('pork_chops', 'Pork chops'),
    ('sausages', 'Sausages'),
    ('cooked_ham', 'Cooked ham'),
    ('serrano_ham', 'Serrano ham'),
    ('sliced_turkey', 'Sliced turkey'),
    ('salmon', 'Salmon'),
    ('hake', 'Hake'),
    ('tuna_steaks', 'Tuna steaks'),
    ('prawns', 'Prawns'),
    ('frozen_fish', 'Frozen fish'),
    ('tofu', 'Tofu'),
    ('veggie_burgers', 'Veggie burgers'),
    ('natural_yogurt', 'Natural yogurt'),
    ('greek_yogurt', 'Greek yogurt'),
    ('fruit_yogurt', 'Fruit yogurt'),
    ('plant_milk', 'Plant-based milk'),
    ('cream', 'Cooking cream'),
    ('cottage_cheese', 'Fresh cheese'),
    ('mozzarella', 'Mozzarella'),
    ('grated_cheese', 'Grated cheese'),
    ('cream_cheese', 'Cream cheese'),
    ('margarine', 'Margarine'),
    ('egg_whites', 'Egg whites'),
    ('dairy_desserts', 'Dairy desserts'),
    ('oats', 'Oats'),
    ('breadcrumbs', 'Breadcrumbs'),
    ('tortilla_wraps', 'Tortilla wraps'),
    ('crackers', 'Crackers'),
    ('quinoa', 'Quinoa'),
    ('couscous', 'Couscous'),
    ('noodles', 'Noodles'),
    ('lentils', 'Lentils'),
    ('chickpeas', 'Chickpeas'),
    ('canned_peas', 'Canned peas'),
    ('canned_tuna', 'Canned tuna'),
    ('canned_sardines', 'Canned sardines'),
    ('tomato_sauce', 'Tomato sauce'),
    ('crushed_tomato', 'Crushed tomatoes'),
    ('tomato_paste', 'Tomato paste'),
    ('mayonnaise', 'Mayonnaise'),
    ('ketchup', 'Ketchup'),
    ('mustard', 'Mustard'),
    ('vinegar', 'Vinegar'),
    ('sunflower_oil', 'Sunflower oil'),
    ('sugar', 'Sugar'),
    ('brown_sugar', 'Brown sugar'),
    ('baking_powder', 'Baking powder'),
    ('yeast', 'Baker''s yeast'),
    ('cocoa_powder', 'Cocoa powder'),
    ('jam', 'Jam'),
    ('peanut_butter', 'Peanut butter'),
    ('dried_fruit', 'Dried fruit'),
    ('cereal_bars', 'Cereal bars'),
    ('crisps', 'Crisps'),
    ('frozen_pizza', 'Frozen pizza'),
    ('sparkling_water', 'Sparkling water'),
    ('decaf_coffee', 'Decaf coffee'),
    ('herbal_tea', 'Herbal tea'),
    ('iced_tea', 'Iced tea'),
    ('energy_drinks', 'Energy drinks'),
    ('tonic_water', 'Tonic water'),
    ('isotonic_drink', 'Isotonic drink'),
    ('kombucha', 'Kombucha'),
    ('cider', 'Cider'),
    ('sparkling_wine', 'Sparkling wine'),
    ('spirits', 'Spirits'),
    ('laundry_detergent', 'Laundry detergent'),
    ('fabric_softener', 'Fabric softener'),
    ('stain_remover', 'Stain remover'),
    ('bleach', 'Bleach'),
    ('disinfectant', 'Disinfectant'),
    ('multipurpose_cleaner', 'Multipurpose cleaner'),
    ('glass_cleaner', 'Glass cleaner'),
    ('degreaser', 'Degreaser'),
    ('toilet_cleaner', 'Toilet cleaner'),
    ('dishwasher_tablets', 'Dishwasher tablets'),
    ('dishwasher_salt', 'Dishwasher salt'),
    ('dishcloths', 'Cleaning cloths'),
    ('rubber_gloves', 'Rubber gloves'),
    ('aluminium_foil', 'Aluminium foil'),
    ('baking_paper', 'Baking paper'),
    ('cling_film', 'Cling film'),
    ('paper_towels', 'Kitchen roll'),
    ('napkins', 'Napkins'),
    ('tissues', 'Tissues'),
    ('deodorant', 'Deodorant'),
    ('shower_gel', 'Shower gel'),
    ('conditioner', 'Conditioner'),
    ('dental_floss', 'Dental floss'),
    ('mouthwash', 'Mouthwash'),
    ('toothbrush_heads', 'Toothbrushes or replacement heads'),
    ('cotton_pads', 'Cotton pads'),
    ('feminine_hygiene', 'Feminine hygiene'),
    ('sunscreen', 'Sunscreen'),
    ('insect_repellent', 'Insect repellent'),
    ('first_aid_kit', 'First aid supplies'),
    ('light_bulbs', 'Light bulbs'),
    ('matches', 'Matches or lighter'),
    ('candles', 'Candles'),
    ('air_freshener', 'Air freshener')
) AS translated(code, name)
WHERE product.code = translated.code;

