-- Seeds the fixed product catalog. Codes are stable identifiers; the image
-- column points at frontend/src/assets/products/<code>.svg.
INSERT INTO products (id, code, name, image, default_category, default_view, sort_order) VALUES
    (gen_random_uuid(), 'tomato',        'Tomatoes',      'tomato.svg',        'FRESH',     'PRIMARY',   1),
    (gen_random_uuid(), 'onion',         'Onions',        'onion.svg',         'FRESH',     'PRIMARY',   2),
    (gen_random_uuid(), 'garlic',        'Garlic',        'garlic.svg',        'FRESH',     'SECONDARY', 3),
    (gen_random_uuid(), 'potato',        'Potatoes',      'potato.svg',        'FRESH',     'PRIMARY',   4),
    (gen_random_uuid(), 'carrot',        'Carrots',       'carrot.svg',        'FRESH',     'SECONDARY', 5),
    (gen_random_uuid(), 'leafy_greens',  'Leafy greens',  'leafy_greens.svg',  'FRESH',     'SECONDARY', 6),
    (gen_random_uuid(), 'bell_pepper',   'Bell peppers',  'bell_pepper.svg',   'FRESH',     'SECONDARY', 7),
    (gen_random_uuid(), 'cucumber',      'Cucumber',      'cucumber.svg',      'FRESH',     'OTHER',     8),
    (gen_random_uuid(), 'broccoli',      'Broccoli',      'broccoli.svg',      'FRESH',     'OTHER',     9),
    (gen_random_uuid(), 'mushroom',      'Mushrooms',     'mushroom.svg',      'FRESH',     'OTHER',     10),
    (gen_random_uuid(), 'avocado',       'Avocado',       'avocado.svg',       'FRESH',     'OTHER',     11),
    (gen_random_uuid(), 'banana',        'Bananas',       'banana.svg',        'FRESH',     'PRIMARY',   12),
    (gen_random_uuid(), 'apple',         'Apples',        'apple.svg',         'FRESH',     'PRIMARY',   13),
    (gen_random_uuid(), 'orange',        'Oranges',       'orange.svg',        'FRESH',     'SECONDARY', 14),
    (gen_random_uuid(), 'lemon',         'Lemons',        'lemon.svg',         'FRESH',     'SECONDARY', 15),
    (gen_random_uuid(), 'strawberry',    'Strawberries',  'strawberry.svg',    'FRESH',     'OTHER',     16),
    (gen_random_uuid(), 'milk',          'Milk',          'milk.svg',          'FRESH',     'PRIMARY',   17),
    (gen_random_uuid(), 'cheese',        'Cheese',        'cheese.svg',        'FRESH',     'PRIMARY',   18),
    (gen_random_uuid(), 'butter',        'Butter',        'butter.svg',        'FRESH',     'SECONDARY', 19),
    (gen_random_uuid(), 'eggs',          'Eggs',          'eggs.svg',          'FRESH',     'PRIMARY',   20),
    (gen_random_uuid(), 'chicken',       'Chicken',       'chicken.svg',       'FRESH',     'PRIMARY',   21),
    (gen_random_uuid(), 'red_meat',      'Red meat',      'red_meat.svg',      'FRESH',     'SECONDARY', 22),
    (gen_random_uuid(), 'bacon',         'Bacon',         'bacon.svg',         'FRESH',     'OTHER',     23),
    (gen_random_uuid(), 'fish',          'Fish',          'fish.svg',          'FRESH',     'SECONDARY', 24),
    (gen_random_uuid(), 'bread',         'Bread',         'bread.svg',         'FRESH',     'PRIMARY',   25),

    (gen_random_uuid(), 'pasta',         'Pasta',         'pasta.svg',         'PANTRY',    'PRIMARY',   26),
    (gen_random_uuid(), 'rice',          'Rice',          'rice.svg',          'PANTRY',    'PRIMARY',   27),
    (gen_random_uuid(), 'flour',         'Flour',         'flour.svg',         'PANTRY',    'SECONDARY', 28),
    (gen_random_uuid(), 'salt',          'Salt',          'salt.svg',          'PANTRY',    'SECONDARY', 29),
    (gen_random_uuid(), 'olive_oil',     'Olive oil',     'olive_oil.svg',     'PANTRY',    'PRIMARY',   30),
    (gen_random_uuid(), 'canned_food',   'Canned food',   'canned_food.svg',   'PANTRY',    'SECONDARY', 31),
    (gen_random_uuid(), 'beans',         'Beans',         'beans.svg',         'PANTRY',    'SECONDARY', 32),
    (gen_random_uuid(), 'sweetcorn',     'Sweetcorn',     'sweetcorn.svg',     'PANTRY',    'OTHER',     33),
    (gen_random_uuid(), 'nuts',          'Nuts',          'nuts.svg',          'PANTRY',    'OTHER',     34),
    (gen_random_uuid(), 'honey',         'Honey',         'honey.svg',         'PANTRY',    'OTHER',     35),
    (gen_random_uuid(), 'cereal',        'Cereal',        'cereal.svg',        'PANTRY',    'SECONDARY', 36),
    (gen_random_uuid(), 'cookies',       'Cookies',       'cookies.svg',       'PANTRY',    'OTHER',     37),
    (gen_random_uuid(), 'chocolate',     'Chocolate',     'chocolate.svg',     'PANTRY',    'OTHER',     38),
    (gen_random_uuid(), 'popcorn',       'Popcorn',       'popcorn.svg',       'PANTRY',    'OTHER',     39),
    (gen_random_uuid(), 'spices',        'Spices',        'spices.svg',        'PANTRY',    'OTHER',     40),

    (gen_random_uuid(), 'water',         'Water',         'water.svg',         'DRINKS',    'PRIMARY',   41),
    (gen_random_uuid(), 'coffee',        'Coffee',        'coffee.svg',        'DRINKS',    'PRIMARY',   42),
    (gen_random_uuid(), 'tea',           'Tea',           'tea.svg',           'DRINKS',    'SECONDARY', 43),
    (gen_random_uuid(), 'juice',         'Juice',         'juice.svg',         'DRINKS',    'SECONDARY', 44),
    (gen_random_uuid(), 'soft_drinks',   'Soft drinks',   'soft_drinks.svg',   'DRINKS',    'OTHER',     45),
    (gen_random_uuid(), 'beer',          'Beer',          'beer.svg',          'DRINKS',    'OTHER',     46),
    (gen_random_uuid(), 'wine',          'Wine',          'wine.svg',          'DRINKS',    'OTHER',     47),

    (gen_random_uuid(), 'hand_soap',     'Hand soap',     'hand_soap.svg',     'HOME_CARE', 'PRIMARY',   48),
    (gen_random_uuid(), 'shampoo',       'Shampoo',       'shampoo.svg',       'HOME_CARE', 'SECONDARY', 49),
    (gen_random_uuid(), 'toothpaste',    'Toothpaste',    'toothpaste.svg',    'HOME_CARE', 'SECONDARY', 50),
    (gen_random_uuid(), 'dish_soap',     'Dish soap',     'dish_soap.svg',     'HOME_CARE', 'PRIMARY',   51),
    (gen_random_uuid(), 'sponges',       'Sponges',       'sponges.svg',       'HOME_CARE', 'SECONDARY', 52),
    (gen_random_uuid(), 'floor_cleaner', 'Floor cleaner', 'floor_cleaner.svg', 'HOME_CARE', 'OTHER',     53),
    (gen_random_uuid(), 'toilet_paper',  'Toilet paper',  'toilet_paper.svg',  'HOME_CARE', 'PRIMARY',   54),
    (gen_random_uuid(), 'bin_bags',      'Bin bags',      'bin_bags.svg',      'HOME_CARE', 'SECONDARY', 55),
    (gen_random_uuid(), 'razors',        'Razors',        'razors.svg',        'HOME_CARE', 'OTHER',     56),
    (gen_random_uuid(), 'batteries',     'Batteries',     'batteries.svg',     'HOME_CARE', 'OTHER',     57)
ON CONFLICT (code) DO NOTHING;
