#!/usr/bin/env bash
# Assembles .env.<environment> from the versioned manifests.
#
#   environments/images.manifest.env    third-party images (all environments)
#   environments/<env>.manifest.env     application image references
#   environments/<env>.config.env       runtime configuration
#
# Secrets are left as CHANGE_ME; fill them in on the target machine.
# The generated file is git-ignored.
#
# Usage: ./scripts/build_env.sh <staging|production>
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENVIRONMENT="${1:-}"

case "$ENVIRONMENT" in
    staging | production) ;;
    *)
        echo "Usage: $0 <staging|production>" >&2
        exit 1
        ;;
esac

TARGET="$INFRA_DIR/.env.$ENVIRONMENT"
SOURCES=(
    "$INFRA_DIR/environments/images.manifest.env"
    "$INFRA_DIR/environments/$ENVIRONMENT.manifest.env"
    "$INFRA_DIR/environments/$ENVIRONMENT.config.env"
)

for source in "${SOURCES[@]}"; do
    [[ -f "$source" ]] || { echo "Missing $source" >&2; exit 1; }
done

{
    echo "# Generated by scripts/build_env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Edit the files under environments/ instead of this one."
    echo ""
    grep -hE '^[A-Z_][A-Z0-9_]*=' "${SOURCES[@]}"
} >"$TARGET"

echo "Wrote $TARGET"

if grep -q 'CHANGE_ME' "$TARGET"; then
    echo "Replace the remaining CHANGE_ME values before deploying:" >&2
    grep -n 'CHANGE_ME' "$TARGET" >&2
fi
